permalink: /discover/:year/:month/:day/:title.html

xcsoar_stable_version: '7.17'
xcsoar_testing_version: null
xcsoar_old_version: '7.16'

server_url: ''
absolute_server_url: '//xcsoar.org'
download_server_url: 'https://download.xcsoar.org/releases'
trac_server_url: 'https://github.com/XCSoar/XCSoar/issues'
mapgen_url: 'http://mapgen.xcsoar.org/'

asset_bundler:
  cdn: '//www.xcsoar.org'
  compress:
    css: 'yui-compressor --type css'
    js: 'yui-compressor --type js'
  markup_templates:
    js: "<script src='{{url}}'> </script>\n"
